# Generated by Django 5.2.8 on 2025-11-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='due_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='followup_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
